classroom/urls.py
from django.urls import path
from .views import HomeView, ThankYouView, ContactFormView,\
    TeacherCreateView,TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns =[
    path('',HomeView.as_view(),name = 'home'),
    path('thankyou/', ThankYouView.as_view(), name='thankyou'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(), name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name= 'list_teacher'),
    path('teacher_detail/<int:pk>',TeacherDetailView.as_view(),name='detail_teacher'),
    path('update_teacher/<int:pk>',TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>',TeacherDeleteView.as_view(),name='delete_teacher')

]

school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
]

classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

classroom/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView,\
    CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Teacher

from .forms import ContactForm

# Create your views here.
def home_view(request):
    return render(request,'classroom/home.html')

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/Thankyou.html'


class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:thankyou')

class TeacherListView(ListView):
    model = Teacher
    queryset = Teacher.objects.order_by('first_name')
    context_object_name = "teacher_list"

class TeacherDetailView(DetailView):
    # return only one model entry pk
    # model_detail.html
    model = Teacher
    #PK --> {{teacher}}

class TeacherUpdateView(UpdateView):
    #Share model form.html --- PK
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    # form --> confirm Delete button
    #default template name:
    # model_confirm_delete.html
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    success_url = reverse_lazy('classroom:thankyou')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

classroom/templates/classroom/Thankyou.html
<h1>Thank You HTML</h1>

classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit"value="Submit">
</form>

classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>
<ul>
    <li>
        <a href="{% url 'classroom:thankyou' %}">Thank You Page Link</a>
    </li>
    <li>
        <a href="{% url 'classroom:contact' %}">Contact  Form Page Link</a>
    </li>
    <li>
        <a href="{% url 'classroom:create_teacher' %}">Create Teacher Page Link</a>
    </li>
    <li>
        <a href="{% url 'classroom:list_teacher' %}">List Teacher Page Link</a>
    </li>
</ul>

classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure want to delete this teacher?</h1>
<h2>{{teacher}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>Detail view for a teacher</h1>
{{teacher}}

classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

classroom/templates/classroom/teacher_list.html
<h1> List of teacher (ListView)</h1>
<ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
            </li>
            <ul>
                <li>
                    <a href="/classroom/update_teacher/{{teacher.id}}">Update Information for {{teacher.first_name}}</a>
                </li>
                <li>
                    <a href="/classroom/delete_teacher/{{teacher.id}}">DELETE</a>
                </li>
            </ul>


    {% endfor %}
</ul>